"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
type Role="dj"|"client"; type Gig={id:string;title:string;description:string|null;event_date:string;start_time:string|null;end_time:string|null;location:string;budget_min:number|null;budget_max:number|null;genres:string[];status:string};
export default function Dashboard(){const router=useRouter();const[role,setRole]=useState<Role|null>(null);const[name,setName]=useState("");const[gigs,setGigs]=useState<Gig[]>([]);const[message,setMessage]=useState("");const[form,setForm]=useState({title:"",description:"",event_date:"",start_time:"",end_time:"",location:"",budget_min:"",budget_max:"",genres:""});const supabase=getSupabaseBrowserClient();
async function load(){const{data:auth}=await supabase.auth.getUser();if(!auth.user){router.push("/auth");return}const{data:user}=await supabase.from("users").select("role").eq("id",auth.user.id).single();if(!user){setMessage("Your account profile is incomplete.");return}setRole(user.role);if(user.role==="dj"){const{data}=await supabase.from("dj_profiles").select("dj_name").eq("user_id",auth.user.id).single();setName(data?.dj_name||"DJ");const{data:open}=await supabase.from("gigs").select("*").eq("status","open").order("event_date");setGigs(open||[])}else{const{data}=await supabase.from("client_profiles").select("name").eq("user_id",auth.user.id).single();setName(data?.name||"Client");const{data:own}=await supabase.from("gigs").select("*").eq("client_id",auth.user.id).order("event_date");setGigs(own||[])}}useEffect(()=>{load()},[]);
async function createGig(e:FormEvent){e.preventDefault();const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{error}=await supabase.from("gigs").insert({client_id:auth.user.id,title:form.title,description:form.description||null,event_date:form.event_date,start_time:form.start_time||null,end_time:form.end_time||null,location:form.location,budget_min:form.budget_min?Number(form.budget_min):null,budget_max:form.budget_max?Number(form.budget_max):null,genres:form.genres.split(",").map(x=>x.trim()).filter(Boolean),status:"open"});setMessage(error?error.message:"Gig posted!");if(!error){setForm({title:"",description:"",event_date:"",start_time:"",end_time:"",location:"",budget_min:"",budget_max:"",genres:""});load()}}
async function apply(gigId:string){const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{error}=await supabase.from("gig_applications").insert({gig_id:gigId,dj_id:auth.user.id,message:"I’m interested in this gig."});setMessage(error?error.message:"Application sent!")}
async function logout(){await supabase.auth.signOut();router.push("/")}
if(!role)return <main className="center-page"><div className="card"><p>Loading your HOVERBOARD dashboard…</p></div></main>;
return <main className="dashboard-page"><header className="topbar"><div><span className="brand">HOVERBOARD</span><span className="muted"> · {role==="dj"?"DJ":"Client"} Dashboard</span></div><button onClick={logout}>Log out</button></header><section className="dashboard-content"><div className="hero-small"><p className="eyebrow">WELCOME</p><h1>Hey, {name}.</h1><p>{role==="dj"?"Find your next gig.":"Put your next gig on the Board."}</p></div>{message&&<div className="notice">{message}</div>}{role==="client"?<><section className="card"><h2>Post a gig</h2><form onSubmit={createGig} className="form grid-form"><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Date<input required type="date" value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></label><label>Start<input type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/></label><label>End<input type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></label><label>Min budget<input type="number" min="0" value={form.budget_min} onChange={e=>setForm({...form,budget_min:e.target.value})}/></label><label>Max budget<input type="number" min="0" value={form.budget_max} onChange={e=>setForm({...form,budget_max:e.target.value})}/></label><label>Genres<input value={form.genres} onChange={e=>setForm({...form,genres:e.target.value})}/></label><label className="full">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary full">Post gig</button></form></section><section><h2>Your gigs</h2><div className="gig-grid">{gigs.map(g=><article className="card gig-card" key={g.id}><p className="eyebrow">{g.status}</p><h3>{g.title}</h3><p>{g.event_date} · {g.location}</p></article>)}</div></section></>:<section><h2>Open gigs</h2><div className="gig-grid">{gigs.length?gigs.map(g=><article className="card gig-card" key={g.id}><p className="eyebrow">{g.event_date}</p><h3>{g.title}</h3><p>{g.description||"No description yet."}</p><p><strong>{g.location}</strong></p><p>{g.start_time||"Time TBD"}{g.end_time?` – ${g.end_time}`:""}</p><p>{g.budget_min||g.budget_max?`$${g.budget_min||0}–$${g.budget_max||g.budget_min}`:"Budget not listed"}</p><button className="primary" onClick={()=>apply(g.id)}>Apply</button></article>):<div className="card"><p>No open gigs yet.</p></div>}</div></section>}</section></main>}
